version: '3.7'

services:
     
  redis-master:
    image: redis:7-alpine
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"
 
  redis-slave:
    image: redis:7-alpine
    command: redis-server --slaveof redis-master 6379
    deploy:  
      replicas: 2
      placement:
            max_replicas_per_node: 1
    links:
      - redis-master
    volumes:
      - "./.data:/data"
     
  redis-sentinel:
    build: 
      context: ./redis-sentinel
    deploy:  
      replicas: 3
      placement:
            max_replicas_per_node: 1
    links:
      - redis-master
